# Generated by Django 2.2.1 on 2019-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColdWaterTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ed_building1', models.FloatField()),
                ('ed_building2', models.FloatField()),
                ('ed_building3', models.FloatField()),
                ('ed_building4', models.FloatField()),
                ('ed_building5', models.FloatField()),
                ('ed_building6', models.FloatField()),
                ('ed_building7', models.FloatField()),
                ('garage', models.FloatField()),
                ('sport_building', models.FloatField()),
                ('canteen', models.FloatField()),
                ('hostel1', models.FloatField()),
                ('hostel2', models.FloatField()),
                ('hostel3', models.FloatField()),
                ('hostel4', models.FloatField()),
                ('hostel5', models.FloatField()),
                ('hostel6', models.FloatField()),
                ('hostel7', models.FloatField()),
                ('hostel8', models.FloatField()),
                ('pavilion', models.FloatField()),
                ('car_fleet', models.FloatField()),
                ('boiler_house', models.FloatField()),
                ('institute', models.FloatField()),
            ],
        ),
    ]
