# Generated by Django 2.2.1 on 2019-06-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coldwatertable',
            name='date',
        ),
        migrations.AddField(
            model_name='coldwatertable',
            name='datemounth',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='coldwatertable',
            name='dateyear',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='boiler_house',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='canteen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='car_fleet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='ed_building1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='ed_building2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='ed_building3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='ed_building4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='ed_building5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='ed_building6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='ed_building7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='garage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='hostel1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='hostel2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='hostel3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='hostel4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='hostel5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='hostel6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='hostel7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='hostel8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='institute',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='pavilion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldwatertable',
            name='sport_building',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
