# Generated by Django 2.2.1 on 2019-06-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20190604_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coldwatertable',
            old_name='datemounth',
            new_name='datemonth',
        ),
        migrations.RemoveField(
            model_name='coldwatertable',
            name='ed_building3',
        ),
    ]
