# Generated by Django 2.2.1 on 2019-06-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20190604_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldwatertable',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
