from django.db import models
import datetime

class ColdWaterTable(models.Model):
  dateyear = models.IntegerField(unique=False, default=datetime.date.today().year)
  datemonth = models.PositiveSmallIntegerField(unique=False, default=datetime.date.today().month)
  ed_building1 = models.FloatField(null=True, blank=True)
  ed_building2 = models.FloatField(null=True, blank=True)
  ed_building4 = models.FloatField(null=True, blank=True)
  ed_building5 = models.FloatField(null=True, blank=True)
  ed_building6 = models.FloatField(null=True, blank=True)
  ed_building7 = models.FloatField(null=True, blank=True)
  garage = models.FloatField(null=True, blank=True)
  sport_building = models.FloatField(null=True, blank=True)
  canteen = models.FloatField(null=True, blank=True)
  hostel1 = models.FloatField(null=True, blank=True)
  hostel2 = models.FloatField(null=True, blank=True)
  hostel3 = models.FloatField(null=True, blank=True)
  hostel4 = models.FloatField(null=True, blank=True)
  hostel5 = models.FloatField(null=True, blank=True)
  hostel6 = models.FloatField(null=True, blank=True)
  hostel7 = models.FloatField(null=True, blank=True)
  hostel8 = models.FloatField(null=True, blank=True)
  pavilion = models.FloatField(null=True, blank=True)
  car_fleet = models.FloatField(null=True, blank=True)
  boiler_house = models.FloatField(null=True, blank=True)
  institute = models.FloatField(null=True, blank=True)
  date = models.IntegerField(unique=False, default=0)

class HotWaterTable(models.Model):
  dateyear = models.IntegerField(unique=False, default=datetime.date.today().year)
  datemonth = models.PositiveSmallIntegerField(unique=False, default=datetime.date.today().month)
  hostel7_1 = models.FloatField(null=True, blank=True)
  hostel7_2 = models.FloatField(null=True, blank=True)
  hostel8_1 = models.FloatField(null=True, blank=True)
  hostel8_2 = models.FloatField(null=True, blank=True)
  date = models.IntegerField(unique=False, default=0)

class WarmTable(models.Model):
  dateyear = models.IntegerField(unique=False, default=datetime.date.today().year)
  datemonth = models.PositiveSmallIntegerField(unique=False, default=datetime.date.today().month)
  ed_building1 = models.FloatField(null=True, blank=True)
  hostel7 = models.FloatField(null=True, blank=True)
  hostel8 = models.FloatField(null=True, blank=True)
  boiler_house = models.FloatField(null=True, blank=True)
  institute = models.FloatField(null=True, blank=True)
  date = models.IntegerField(unique=False, default=0)

class TemperatureTable(models.Model):
  dateyear = models.IntegerField(unique=False, default=datetime.date.today().year)
  datemonth = models.PositiveSmallIntegerField(unique=False, default=datetime.date.today().month)
  ed_building1 = models.FloatField(null=True, blank=True)
  ed_building2 = models.FloatField(null=True, blank=True)
  ed_building4 = models.FloatField(null=True, blank=True)
  ed_building5 = models.FloatField(null=True, blank=True)
  ed_building6 = models.FloatField(null=True, blank=True)
  ed_building7 = models.FloatField(null=True, blank=True)
  garage = models.FloatField(null=True, blank=True)
  sport_building = models.FloatField(null=True, blank=True)
  canteen = models.FloatField(null=True, blank=True)
  hostel1 = models.FloatField(null=True, blank=True)
  hostel2 = models.FloatField(null=True, blank=True)
  hostel3 = models.FloatField(null=True, blank=True)
  hostel4 = models.FloatField(null=True, blank=True)
  hostel5 = models.FloatField(null=True, blank=True)
  hostel6 = models.FloatField(null=True, blank=True)
  hostel7 = models.FloatField(null=True, blank=True)
  hostel8 = models.FloatField(null=True, blank=True)
  pavilion = models.FloatField(null=True, blank=True)
  car_fleet = models.FloatField(null=True, blank=True)
  boiler_house = models.FloatField(null=True, blank=True)
  institute = models.FloatField(null=True, blank=True)
  date = models.IntegerField(unique=False, default=0)

class ElectricityTable(models.Model):
  dateyear = models.IntegerField(unique=False, default=datetime.date.today().year)
  datemonth = models.PositiveSmallIntegerField(unique=False, default=datetime.date.today().month)
  ed_building1_1 = models.FloatField(null=True, blank=True)
  ed_building1_2 = models.FloatField(null=True, blank=True)
  ed_building1_3 = models.FloatField(null=True, blank=True)
  ed_building2_1 = models.FloatField(null=True, blank=True)
  ed_building2_2 = models.FloatField(null=True, blank=True)
  ed_building2_3 = models.FloatField(null=True, blank=True)
  ed_building2_4 = models.FloatField(null=True, blank=True)
  ed_building2_5 = models.FloatField(null=True, blank=True)
  ed_building2_6 = models.FloatField(null=True, blank=True)
  ed_building2a_1 = models.FloatField(null=True, blank=True)
  ed_building2a_2 = models.FloatField(null=True, blank=True)
  ed_building2a_3 = models.FloatField(null=True, blank=True)
  ed_building2a_4 = models.FloatField(null=True, blank=True)
  ed_building2a_5 = models.FloatField(null=True, blank=True)
  ed_building2a_6 = models.FloatField(null=True, blank=True)
  ed_building6_1 = models.FloatField(null=True, blank=True)
  ed_building6_2 = models.FloatField(null=True, blank=True)
  ed_building6_3 = models.FloatField(null=True, blank=True)
  ed_building6_4 = models.FloatField(null=True, blank=True)
  ed_building7_1 = models.FloatField(null=True, blank=True)
  ed_building7_2 = models.FloatField(null=True, blank=True)
  barn = models.FloatField(null=True, blank=True)
  canteen = models.FloatField(null=True, blank=True)
  garage_1 = models.FloatField(null=True, blank=True)
  garage_2 = models.FloatField(null=True, blank=True)
  garage_3 = models.FloatField(null=True, blank=True)
  proving_ground = models.FloatField(null=True, blank=True)
  pavilion = models.FloatField(null=True, blank=True)
  hostel1 = models.FloatField(null=True, blank=True)
  hostel2 = models.FloatField(null=True, blank=True)
  hostel3 = models.FloatField(null=True, blank=True)
  hostel4 = models.FloatField(null=True, blank=True)
  hostel5 = models.FloatField(null=True, blank=True)
  hostel6_1 = models.FloatField(null=True, blank=True)
  hostel6_2 = models.FloatField(null=True, blank=True)
  hostel7_1 = models.FloatField(null=True, blank=True)
  hostel7_2 = models.FloatField(null=True, blank=True)
  hostel8_1 = models.FloatField(null=True, blank=True)
  hostel8_2 = models.FloatField(null=True, blank=True)
  hostel8_3 = models.FloatField(null=True, blank=True)
  TP38_1 = models.FloatField(null=True, blank=True)
  TP38_2 = models.FloatField(null=True, blank=True)
  TP38_3 = models.FloatField(null=True, blank=True)
  TP72_1 = models.FloatField(null=True, blank=True)
  TP72_2 = models.FloatField(null=True, blank=True)
  TP72_3 = models.FloatField(null=True, blank=True)
  institute = models.FloatField(null=True, blank=True)
  date = models.IntegerField(unique=False, default=0)










