# Generated by Django 2.2.1 on 2019-06-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_email', models.EmailField(max_length=254, unique=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'coldwater_manager'), (3, 'hotwater_manager'), (4, 'warm_manager'), (5, 'electricity_manager'), (6, 'temperature_manager')], default=1, primary_key=True, serialize=False)),
                ('is_staff', models.BooleanField()),
            ],
        ),
    ]
