# Generated by Django 2.2.2 on 2019-06-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'coldwater_manager'), (2, 'hotwater_manager'), (3, 'warm_manager'), (4, 'electricity_manager'), (5, 'temperature_manager')], default=1, primary_key=True, serialize=False),
        ),
    ]
